const std = @import("std");

const mem = std.mem;
const testing = std.testing;
const expect = testing.expect;
const pageAllocator = std.heap.page_allocator;

pub const Token = struct {
    tag: Tag,
    loc: Loc,

    pub const Loc = struct {
        start: usize,
        end: usize,
    };

    pub const Tag = enum {
        eof,
        err,
        shebang,
        line_comment,
        block_comment,
        markup,
        text,
        space,
        linebreak,
        paragrah_break,
        escape,
        shorthand,
        smartquote,
        strong,
        empasized,
        raw,
        raw_lang,
        raw_delim,
        raw_trimmed,
        link,
        label,
        ref,
        ref_marker,
        heading,
        heading_marker,
        list_item,
        list_marker,
        enum_item,
        enum_marker,
        term_item,
        term_marker,
        eq,

        math,
        math_text,
        math_ident,
        math_shorthand,
        math_alignpoint,
        math_call,
        math_args,
        math_delim,
        math_attach,
        math_primes,
        math_frac,
        math_root,

        hash,
        l_brace,
        r_brace,
        l_bracket,
        r_bracket,
        l_paren,
        r_paren,
        comma,
        colon,
        semicolon,
        star,
        underscore,
        dollar,
        plus,
        minus,
        slash,
        caret,
        dot,
        equal,
        equal_equal,
        bang_equal,
        angle_bracket_left,
        angle_bracket_left_equal,
        angle_bracket_right,
        angle_bracket_right_equal,
        plus_equal,
        minus_euqal,
        asterisk_equal,
        slash_equal,
        dot_dot,
        equal_angle_bracket_left,
        root,
        bang,

        op_not,
        op_and,
        op_or,

        none,
        auto,

        keyword_let,
        keyword_set,
        keyword_show,
        keyword_context,
        keyword_if,
        keyword_else,
        keyword_for,
        keyword_in,
        keyword_while,
        keyword_break,
        keyword_continue,
        keyword_return,
        keyword_import,
        keyword_include,
        keyword_as,

        code,
        identifier,
        boolean,
        int,
        float,
        numeric,
        str,
        code_block,
        content_block,
        parenthesized,
        array,
        dict,
        named,
        keyed,
        unary,
        binary,
        field_access,
        func_call,
    };
};
